[functions]
directory = "reason_node_output/reason_netlify_functions"
node_bundler = "esbuild"
external_node_modules = [
    "@glennsl",
    "melange",
    "melange-fetch",
    "melange.belt",
    "melange.runtime",
]
