// Generated by Melange
'use strict';


function handler(_event, _context, callback) {
  return callback(null, {
              statusCode: 200,
              body: JSON.stringify({
                    message: "Hello World"
                  })
            });
}

exports.handler = handler;
/* No side effect */
