// Generated by Melange
"use strict";

var Curry = require("melange.runtime/curry.js");
var Fetch = require("melange-fetch/./Fetch.js");

require("isomorphic-fetch");

function fetchJoke(param) {
  return fetch(
    "https://icanhazdadjoke.com/",
    Curry._2(
      Fetch.RequestInit.make(
        /* Get */ 0,
        {
          "Content-Type": "application/json",
        },
        undefined,
        undefined,
        undefined,
        undefined
      )(undefined, undefined, undefined, undefined, undefined),
      undefined,
      undefined
    )
  )
    .then(function (prim) {
      return prim.json();
    })
    .then(function (json) {
      console.log("Json", json);
      return Promise.resolve({
        TAG: /* Ok */ 0,
        _0: json,
      });
    })
    .catch(function (err) {
      return Promise.resolve({
        TAG: /* Error */ 1,
        _0: err,
      });
    });
}

function handler($$event, _context, callback) {
  console.log("Event", $$event);
  return fetchJoke(undefined).then(function (res) {
    if (res.TAG === /* Ok */ 0) {
      var data = res._0;
      console.log("Data", data);
      var body = JSON.stringify(data);
      callback(
        undefined,
        {
          statusCode: 200,
          body: body,
        },
        undefined
      );
    } else {
      var body$1 = JSON.stringify(res._0);
      callback(
        undefined,
        {
          statusCode: 500,
          body: body$1,
        },
        undefined
      );
    }
    return Promise.resolve(undefined);
  });
}

exports.fetchJoke = fetchJoke;
exports.handler = handler;
/*  Not a pure module */
