// Generated by Melange


((import * as fetch from 'isomorphic-fetch'));

function fetchJoke(param) {
  return fetch("https://icanhazdadjoke.com/").then(function (prim) {
                  return prim.json();
                }).then(function (json) {
                return Promise.resolve({
                            TAG: /* Ok */0,
                            _0: json
                          });
              }).catch(function (err) {
              return Promise.resolve({
                          TAG: /* Error */1,
                          _0: err
                        });
            });
}

function handler(request, _response) {
  console.log("Request", request);
}

export {
  fetchJoke ,
  handler ,
}
/*  Not a pure module */
